pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'bugtracker-backend:latest'
                    alwaysPull false
                    args '-e GOCACHE=/tmp/go-build -e GOPATH=/tmp/go'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        set -o pipefail
                        go install github.com/jstemmer/go-junit-report@latest
                        export PATH="/tmp/go/bin:$PATH"
                        go test -v ./... 2>&1 | go-junit-report > test-results.xml

                        #Generate coverage report
                        go test -coverprofile=coverage.out -covermode=atomic ./...
                        go tool cover -html=coverage.out -o coverage.html

                        mkdir -p reports
                        mv coverage.html reports/
                    '''
                }
            }
            post {
                always {
                    junit testResults: 'bugtracker-backend/test-results.xml', allowEmptyResults: true
                    publishHTML target: [
                        reportDir: 'bugtracker-backend/reports',
                        reportFiles: 'coverage.html',
                        reportName: 'Backend Coverage Report'
                    ]
    
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'bugtracker-frontend-test:latest'
                    alwaysPull false
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                        mkdir -p reports
                        mv coverage reports/    
                    '''
                }
            }

            post {
             always {
                junit testResults: 'bugtracker-frontend/test-results.xml', allowEmptyResults: true
                publishHTML target: [
                    reportDir: 'bugtracker-frontend/reports/coverage',
                    reportFiles: 'index.html',
                    reportName: 'Frontend Coverage Report'
                ]
                    }
                }
        }

    }
}