pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'bugtracker-backend:latest'
                    alwaysPull false
                    args '-e GOCACHE=/tmp/go-build -e GOPATH=/tmp/go'
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'bugtracker-frontend-test:latest'
                    alwaysPull false
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh 'npm ci'
                    sh 'npm test'
                }
            }

            post {
             always {
                junit testResults: 'bugtracker-frontend/test-results.xml', allowEmptyResults: true
                    }
                }
        }

    }
}